#!/usr/bin/env python3
"""Generate C glue from a Python HM64 mod file."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


class ApiField:
    def __init__(
        self,
        python_paths: tuple[tuple[str, ...], ...],
        c_path: str,
        type_name: str,
        minimum: int,
        maximum: int,
    ) -> None:
        self.python_paths = python_paths
        self.c_path = c_path
        self.type_name = type_name
        self.minimum = minimum
        self.maximum = maximum

    @property
    def primary_python_path(self) -> tuple[str, ...]:
        return self.python_paths[0]

    @property
    def dotted_python_path(self) -> str:
        return "api." + ".".join(self.primary_python_path)


# Add new Python-facing API values here. Each field maps one or more Python
# assignment paths onto the C field that generatedMod.c should write.
API_FIELDS = [
    ApiField(
        python_paths=(("time", "speed"), ("gametimespeed",)),
        c_path="api.config.time.speed",
        type_name="u16",
        minimum=0,
        maximum=0xFFFF,
    ),
]


class ApiGroup:
    def __init__(self, root: "ApiSettings", path: tuple[str, ...] = ()) -> None:
        object.__setattr__(self, "_root", root)
        object.__setattr__(self, "_path", path)

    def __getattr__(self, name: str) -> "ApiGroup":
        return ApiGroup(self._root, self._path + (name,))

    def __setattr__(self, name: str, value: int) -> None:
        self._root.set_value(self._path + (name,), value)


class ApiSettings(ApiGroup):
    def __init__(self) -> None:
        object.__setattr__(self, "_values", {})
        super().__init__(self)

    def set_value(self, path: tuple[str, ...], value: int) -> None:
        field = self.get_field(path)

        if not isinstance(value, int):
            raise TypeError(f"{field.dotted_python_path} must be an integer")
        if value < field.minimum or value > field.maximum:
            raise ValueError(f"{field.dotted_python_path} must fit in a {field.type_name}")

        self._values[field.primary_python_path] = value

    def get_field(self, path: tuple[str, ...]) -> ApiField:
        for field in API_FIELDS:
            if path in field.python_paths:
                return field
        raise AttributeError(f"unknown mod API field: api.{'.'.join(path)}")

    def configured_values(self) -> list[tuple[ApiField, int]]:
        configured = []
        for field in API_FIELDS:
            path = field.primary_python_path
            if path in self._values:
                configured.append((field, self._values[path]))
        return configured


def resolve_mod_path(path: Path) -> Path:
    if path.is_dir():
        path = path / "mod.py"
    if not path.exists():
        raise SystemExit(f"mod file not found: {path}")
    return path


def load_mod(path: Path | None) -> ApiSettings:
    api = ApiSettings()

    if path is None:
        return api

    path = resolve_mod_path(path)
    namespace = {
        "__file__": str(path),
        "__name__": "__hm64_mod__",
        "api": api,
    }

    try:
        code = compile(path.read_text(), str(path), "exec")
        exec(code, namespace)
    except Exception as exc:
        raise SystemExit(f"{path}: {exc}") from exc

    return api


def render_c(api: ApiSettings, mod_path: Path | None) -> str:
    source = "no Python mod selected" if mod_path is None else str(resolve_mod_path(mod_path))
    lines = [
        "/* Auto-generated by tools/modding/build_mod.py. */",
        f"/* Source: {source} */",
        "",
        '#include "common.h"',
        "",
        '#include "modding/modApi.h"',
        "",
        "void applyGeneratedModSettings(void) {",
    ]

    for field, value in api.configured_values():
        lines.append(f"    {field.c_path} = {value};")

    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate C glue from a Python HM64 mod")
    parser.add_argument("--mod", type=Path, help="Python mod file, or directory containing mod.py")
    parser.add_argument("-o", "--output", type=Path, required=True, help="generated C output")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    api = load_mod(args.mod)
    output = render_c(api, args.mod)
    args.output.parent.mkdir(parents=True, exist_ok=True)

    if args.output.exists() and args.output.read_text() == output:
        action = "Kept"
    else:
        args.output.write_text(output)
        action = "Wrote"

    if args.mod is None:
        print(f"{action} {args.output} with default mod settings")
    else:
        print(f"{action} {args.output} from {resolve_mod_path(args.mod)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
